import type {
  Application,
  Applicant,
  CreditReport,
  IncomeData,
  LoanRequest,
  RiskAssessment,
  FeatureContribution,
  DataProvenance,
  AuditEvent,
  ScenarioInput,
} from "./types"

const applicant: Applicant = {
  id: "app-001",
  name: "Sarah Chen",
  email: "s.chen@email.com",
  phone: "(555) 123-4567",
  ssn_last_four: "4589",
  created_at: "2024-01-15T10:30:00Z",
}

const creditReport: CreditReport = {
  credit_score: 712,
  credit_utilization: 0.34,
  payment_history_percent: 0.96,
  derogatory_marks: 1,
  hard_inquiries: 2,
  total_accounts: 8,
  oldest_account_years: 7.5,
}

const incomeData: IncomeData = {
  annual_income: 85000,
  employment_length_months: 36,
  debt_to_income: 0.28,
  monthly_debt_payments: 1983,
}

const loanRequest: LoanRequest = {
  amount: 25000,
  purpose: "Debt Consolidation",
  term_months: 60,
}

const riskAssessment: RiskAssessment = {
  id: "risk-001",
  applicant_id: "app-001",
  score: 724,
  probability_of_default: 0.087,
  risk_tier: "medium",
  confidence: 0.89,
  recommended_action: "review",
  timestamp: "2024-01-15T10:31:45Z",
}

const featureContributions: FeatureContribution[] = [
  {
    feature_name: "credit_score",
    display_name: "Credit Score",
    value: 712,
    contribution: 0.15,
    direction: "negative",
    importance_rank: 1,
  },
  {
    feature_name: "debt_to_income",
    display_name: "Debt-to-Income Ratio",
    value: "28%",
    contribution: 0.12,
    direction: "positive",
    importance_rank: 2,
  },
  {
    feature_name: "payment_history",
    display_name: "Payment History",
    value: "96%",
    contribution: 0.09,
    direction: "negative",
    importance_rank: 3,
  },
  {
    feature_name: "credit_utilization",
    display_name: "Credit Utilization",
    value: "34%",
    contribution: 0.08,
    direction: "positive",
    importance_rank: 4,
  },
  {
    feature_name: "employment_length",
    display_name: "Employment Length",
    value: "3 years",
    contribution: 0.06,
    direction: "negative",
    importance_rank: 5,
  },
  {
    feature_name: "hard_inquiries",
    display_name: "Hard Inquiries",
    value: 2,
    contribution: 0.04,
    direction: "positive",
    importance_rank: 6,
  },
  {
    feature_name: "derogatory_marks",
    display_name: "Derogatory Marks",
    value: 1,
    contribution: 0.03,
    direction: "positive",
    importance_rank: 7,
  },
]

const dataProvenance: DataProvenance[] = [
  {
    field_name: "credit_score",
    source: "Equifax API",
    timestamp: "2024-01-15T10:30:12Z",
    confidence: 0.99,
    verification_status: "verified",
    raw_value: 712,
    transformed_value: 712,
  },
  {
    field_name: "annual_income",
    source: "Plaid Income",
    timestamp: "2024-01-15T10:30:15Z",
    confidence: 0.95,
    verification_status: "verified",
    raw_value: 85234,
    transformed_value: 85000,
  },
  {
    field_name: "employment_length",
    source: "Employer Verification",
    timestamp: "2024-01-14T14:22:00Z",
    confidence: 0.92,
    verification_status: "verified",
    raw_value: "36 months",
    transformed_value: 36,
  },
  {
    field_name: "debt_to_income",
    source: "Calculated",
    timestamp: "2024-01-15T10:30:45Z",
    confidence: 0.88,
    verification_status: "verified",
    raw_value: 0.2798,
    transformed_value: 0.28,
  },
  {
    field_name: "payment_history",
    source: "TransUnion API",
    timestamp: "2024-01-15T10:30:18Z",
    confidence: 0.97,
    verification_status: "verified",
    raw_value: 0.9583,
    transformed_value: 0.96,
  },
]

const auditTrail: AuditEvent[] = [
  {
    id: "evt-001",
    timestamp: "2024-01-15T10:30:00Z",
    action: "Application Received",
    actor: "System",
    details: "New loan application submitted via web portal",
    category: "system",
  },
  {
    id: "evt-002",
    timestamp: "2024-01-15T10:30:12Z",
    action: "Credit Pull Initiated",
    actor: "System",
    details: "Hard inquiry sent to Equifax, TransUnion",
    category: "system",
  },
  {
    id: "evt-003",
    timestamp: "2024-01-15T10:30:15Z",
    action: "Income Verified",
    actor: "Plaid Service",
    details: "Bank statements analyzed, income confirmed",
    category: "system",
  },
  {
    id: "evt-004",
    timestamp: "2024-01-15T10:31:45Z",
    action: "Risk Model Executed",
    actor: "ML Pipeline v2.3.1",
    details: "XGBoost ensemble model, 89% confidence",
    category: "model",
  },
  {
    id: "evt-005",
    timestamp: "2024-01-15T10:32:00Z",
    action: "Manual Review Triggered",
    actor: "System",
    details: "Score within review threshold (700-750)",
    category: "system",
  },
  {
    id: "evt-006",
    timestamp: "2024-01-15T11:15:00Z",
    action: "Analyst Assigned",
    actor: "J. Rodriguez",
    details: "Application assigned for manual review",
    category: "user",
  },
]

export const defaultScenarioInputs: ScenarioInput[] = [
  {
    feature: "credit_score",
    label: "Credit Score",
    min: 300,
    max: 850,
    step: 10,
    current: 712,
    modified: 712,
  },
  {
    feature: "debt_to_income",
    label: "Debt-to-Income Ratio",
    min: 0,
    max: 0.6,
    step: 0.01,
    current: 0.28,
    modified: 0.28,
  },
  {
    feature: "credit_utilization",
    label: "Credit Utilization",
    min: 0,
    max: 1,
    step: 0.01,
    current: 0.34,
    modified: 0.34,
  },
  {
    feature: "employment_length",
    label: "Employment Length",
    min: 0,
    max: 120,
    step: 6,
    current: 36,
    modified: 36,
  },
  {
    feature: "annual_income",
    label: "Annual Income",
    min: 20000,
    max: 250000,
    step: 5000,
    current: 85000,
    modified: 85000,
  },
]

export const mockApplication: Application = {
  id: "app-001",
  applicant,
  credit_report: creditReport,
  income_data: incomeData,
  loan_request: loanRequest,
  risk_assessment: riskAssessment,
  feature_contributions: featureContributions,
  data_provenance: dataProvenance,
  audit_trail: auditTrail,
}

export const mockApplications: Application[] = [
  mockApplication,
  {
    ...mockApplication,
    id: "app-002",
    applicant: {
      ...applicant,
      id: "app-002",
      name: "Michael Torres",
      email: "m.torres@email.com",
      created_at: "2024-01-14T09:15:00Z",
    },
    risk_assessment: {
      ...riskAssessment,
      id: "risk-002",
      score: 845,
      probability_of_default: 0.032,
      risk_tier: "low",
      confidence: 0.94,
      recommended_action: "approve",
    },
    loan_request: {
      amount: 15000,
      purpose: "Home Improvement",
      term_months: 36,
    },
    credit_report: {
      ...creditReport,
      credit_score: 798,
      credit_utilization: 0.15,
      payment_history_percent: 1.0,
      derogatory_marks: 0,
    },
  },
  {
    ...mockApplication,
    id: "app-003",
    applicant: {
      ...applicant,
      id: "app-003",
      name: "Emily Johnson",
      email: "e.johnson@email.com",
      created_at: "2024-01-13T14:45:00Z",
    },
    risk_assessment: {
      ...riskAssessment,
      id: "risk-003",
      score: 512,
      probability_of_default: 0.24,
      risk_tier: "high",
      confidence: 0.78,
      recommended_action: "decline",
    },
    loan_request: {
      amount: 40000,
      purpose: "Business Expansion",
      term_months: 84,
    },
    credit_report: {
      ...creditReport,
      credit_score: 580,
      credit_utilization: 0.72,
      payment_history_percent: 0.82,
      derogatory_marks: 3,
    },
  },
  {
    ...mockApplication,
    id: "app-004",
    applicant: {
      ...applicant,
      id: "app-004",
      name: "David Kim",
      email: "d.kim@email.com",
      created_at: "2024-01-12T11:30:00Z",
    },
    risk_assessment: {
      ...riskAssessment,
      id: "risk-004",
      score: 678,
      probability_of_default: 0.12,
      risk_tier: "medium",
      confidence: 0.85,
      recommended_action: "review",
    },
    loan_request: {
      amount: 30000,
      purpose: "Vehicle Purchase",
      term_months: 48,
    },
    credit_report: {
      ...creditReport,
      credit_score: 695,
      credit_utilization: 0.42,
      payment_history_percent: 0.91,
      derogatory_marks: 1,
    },
  },
  {
    ...mockApplication,
    id: "app-005",
    applicant: {
      ...applicant,
      id: "app-005",
      name: "Jessica Martinez",
      email: "j.martinez@email.com",
      created_at: "2024-01-11T16:20:00Z",
    },
    risk_assessment: {
      ...riskAssessment,
      id: "risk-005",
      score: 892,
      probability_of_default: 0.018,
      risk_tier: "low",
      confidence: 0.97,
      recommended_action: "approve",
    },
    loan_request: {
      amount: 50000,
      purpose: "Debt Consolidation",
      term_months: 60,
    },
    credit_report: {
      ...creditReport,
      credit_score: 820,
      credit_utilization: 0.08,
      payment_history_percent: 1.0,
      derogatory_marks: 0,
    },
    income_data: {
      ...incomeData,
      annual_income: 145000,
      debt_to_income: 0.18,
    },
  },
  {
    ...mockApplication,
    id: "app-006",
    applicant: {
      ...applicant,
      id: "app-006",
      name: "Robert Williams",
      email: "r.williams@email.com",
      created_at: "2024-01-10T08:45:00Z",
    },
    risk_assessment: {
      ...riskAssessment,
      id: "risk-006",
      score: 385,
      probability_of_default: 0.45,
      risk_tier: "critical",
      confidence: 0.91,
      recommended_action: "decline",
    },
    loan_request: {
      amount: 20000,
      purpose: "Medical Expenses",
      term_months: 36,
    },
    credit_report: {
      ...creditReport,
      credit_score: 485,
      credit_utilization: 0.89,
      payment_history_percent: 0.68,
      derogatory_marks: 5,
    },
    income_data: {
      ...incomeData,
      annual_income: 42000,
      debt_to_income: 0.52,
    },
  },
]
